{% set version = '3.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dggridr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dggridR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dggridR/dggridR_{{ version }}.tar.gz
  sha256: 4aa6e58b31209a4578626661bc7583bfad2f1a96fd8ce804d0d6701f10a325a4

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-dplyr >=0.4
    - r-rlang >=0.4
    - r-sf >=1.0
    - r-sp >=1.2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.12
    - r-dplyr >=0.4
    - r-rlang >=0.4
    - r-sf >=1.0
    - r-sp >=1.2

test:
  commands:
    - $R -e "library('dggridR')"           # [not win]
    - "\"%R%\" -e \"library('dggridR')\""  # [win]

about:
  home: https://github.com/r-barnes/dggridR/
  license: AGPL-3.0-or-later
  summary: Spatial analyses involving binning require that every bin have the same area, but
    this is impossible using a rectangular grid laid over the Earth or over any projection
    of the Earth. Discrete global grids use hexagons, triangles, and diamonds to overcome
    this issue, overlaying the Earth with equally-sized bins. This package provides
    utilities for working with discrete global grids, along with utilities to aid in
    plotting such data.
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - marie59
